### ISSUE TITLE
Complete CFE region and any other data gaps in Cloud Region dataset

### ISSUE THREAD

**Issue by adrianco** [Green-Software-Foundation/real-time-cloud#35]
There is partial data in a few columns in the dataset, tidy them up
https://docs.google.com/spreadsheets/d/1RKjD4CuI5bd7JTj-9Mi1-ZhTIc6OW7TH9hUvLPbLsPA/edit#gid=0

**Comment by vielmetti** [comment]
Noting that "geofeed" data might be useful for this task.

About Geofeed: https://ipregistry.co/blog/geofeeds

The Geofeed standard: https://datatracker.ietf.org/doc/html/rfc8805

an example feed, from Equinix Metal: https://geofeed.equinixmetal.com

What it looks like (a simple sample)

```
147.28.206.0/23,NL,NL-NH,Amsterdam,
2604:1380:f0::/44,NL,NL-NH,Amsterdam,
86.109.13.0/24,NL,NL-NH,Amsterdam,
```

**Comment by adrianco** [comment]
Gaps closed
