### ISSUE TITLE
Real-Time-Cloud project logo/icon

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/real-time-cloud#6]
Why: New project requires  icon/logo
What: Real-Time-Cloud is a newly approved project

**Scope of work:**
Create a new icon/logo for the [Real-Time-Cloud project](https://github.com/Green-Software-Foundation/real-time-cloud).

Request date: End of Aug

**Comment by Jenya-design** [comment]
Hi @seanmcilroy29 I'm away August 18-27, I'll provide the update right after I'm back to work
Thank you

**Comment by Jenya-design** [comment]
Hello @seanmcilroy29 
Please check the update attached
There are two options for the logo and overview of all Standards WG projects together


![Image](https://github.com/Green-Software-Foundation/real-time-cloud/assets/69306070/2425547f-57a4-43ab-a3e2-5d2bfe7ae8e2)

![Image](https://github.com/Green-Software-Foundation/real-time-cloud/assets/69306070/5260e04c-5750-4a57-a832-b1ae45edb127)

**Comment by seanmcilroy29** [comment]
@Jenya-design - nice work! 
We'll go with v.01

**Comment by Jenya-design** [comment]
Thank you @seanmcilroy29 
Source files (ai, svg, png) for the v.01 are here
https://drive.google.com/drive/folders/1x7eeLTXqak0S6v4GOcjyMOX_ikgBaGgB?usp=sharing

**Comment by seanmcilroy29** [comment]
Thanks @Jenya-design
